# Generated by Django 5.2.6 on 2025-09-15 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Completo do Evento')),
                ('acronym', models.CharField(max_length=20, verbose_name='Acrónimo')),
                ('website', models.URLField(blank=True, max_length=255, verbose_name='Website do Evento')),
                ('full_description', models.TextField(verbose_name='Descrição Completa')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['acronym'],
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('location', models.CharField(max_length=100, verbose_name='Localização')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Fim')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Edição',
                'verbose_name_plural': 'Edições',
                'ordering': ['-year', '-start_date'],
                'unique_together': {('event', 'year', 'location', 'start_date', 'end_date')},
            },
        ),
    ]
