# Generated by Django 5.2.6 on 2025-10-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='entidade_promotora',
        ),
    ]
