# Generated by Django 5.2.6 on 2025-09-30 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_authors_article_authors'),
        ('events', '0002_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
