# Generated by Django 5.2.7 on 2025-10-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.AddField(
            model_name='event',
            name='promoting_entity',
            field=models.CharField(blank=True, max_length=255, verbose_name='Entidade Promotora'),
        ),
    ]