# Generated by Django 5.2.6 on 2025-10-07 23:22

import apps.articles.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('authors', models.CharField(max_length=500, verbose_name='Autores')),
                ('abstract', models.TextField(blank=True, verbose_name='Resumo')),
                ('keywords', models.CharField(blank=True, help_text='Separe as palavras-chave por vírgula', max_length=255, verbose_name='Palavras-chave')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=apps.articles.models.article_upload_path, verbose_name='Arquivo PDF')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Nome Original do Arquivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='events.edition', verbose_name='Edição')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
            },
        ),
    ]
