# Generated by Django 5.2.6 on 2025-09-19 00:27

import apps.articles.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('authors', models.CharField(max_length=500, verbose_name='Autores')),
                ('abstract', models.TextField(blank=True, verbose_name='Resumo')),
                ('pdf_file', models.FileField(upload_to=apps.articles.models.article_upload_path, verbose_name='Arquivo PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='events.edition', verbose_name='Edição')),
            ],
        ),
    ]
