# Generated by Django 5.2.6 on 2025-09-28 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('events', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='events.edition', verbose_name='Edição'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(related_name='articles', to='events.author', verbose_name='Autores'),
        ),
    ]
