# Generated by Django 5.2.6 on 2025-09-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_edition_remove_article_authors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.CharField(default=1, max_length=500, verbose_name='Autores'),
            preserve_default=False,
        ),
    ]
