# Generated by Django 5.2.7 on 2025-10-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_authors_article_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(blank=True, help_text='Separe as palavras-chave por vírgula', max_length=255, verbose_name='Palavras-chave'),
        ),
    ]
