# Generated by Django 5.2.7 on 2025-10-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Localização (BibTeX)'),
        ),
        migrations.AddField(
            model_name='article',
            name='pages',
            field=models.CharField(blank=True, max_length=50, verbose_name='Páginas'),
        ),
        migrations.AddField(
            model_name='article',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, verbose_name='Publicador (BibTeX)'),
        ),
    ]